import tempfile
import zipfile
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse, PlainTextResponse
from fastapi.staticfiles import StaticFiles

from b2t.api.jobs import EXECUTOR, JobStore, run_job
from b2t.api.schemas import (
    GraphView,
    JobCreated,
    JobView,
    ModelOption,
    ModelsView,
    SaveRequest,
    SaveResult,
    to_view,
)
from b2t.graph import build_graph
from b2t.config import DEFAULT_MODEL, OPEN_MODELS, REPO_ROOT
from b2t.typst_runner import compile_typst
from b2t.llm import ConverterLLM, FakeConverter, OpenAIConverter

SAMPLE_DECK = REPO_ROOT / "tests" / "fixtures" / "sample_deck"
STATIC_DIR = Path(__file__).parent / "static"
FAKE_TYPST = (
    "#set page(width: 16cm, height: 9cm)\n"
    "= Sample\n\nGenerated by the fake converter.\n"
)


def _make_converter(use_fake: bool, model: str) -> ConverterLLM:
    if use_fake:
        return FakeConverter(FAKE_TYPST)
    return OpenAIConverter(model=model or None)


def _safe_target(root: Path, rel: str) -> Path:
    """Resolve rel under root, rejecting any path that escapes root."""
    target = (root / rel).resolve()
    if not target.is_relative_to(root):
        raise HTTPException(status_code=400, detail="invalid path in upload")
    return target


def _reconstruct(files: list[UploadFile], root: Path) -> None:
    """Write each uploaded file under root at its relative path. Reject escapes."""
    root = root.resolve()
    for upload in files:
        target = _safe_target(root, upload.filename or "")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(upload.file.read())


def _zip_dir(directory: Path) -> Path:
    """Zip every file under directory into a fresh temp zip; return its path."""
    zip_path = Path(tempfile.mkdtemp(prefix="b2t_download_")) / "deck.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(directory.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(directory))
    return zip_path


def create_app(store: JobStore | None = None) -> FastAPI:
    load_dotenv()
    app = FastAPI(title="b2t testing UI")
    jobs = store or JobStore()

    @app.post("/api/jobs", response_model=JobCreated)
    async def create_job(
        files: list[UploadFile] = File([]),
        use_fake: bool = Form(False),
        model: str = Form(""),
    ):
        if not files:
            raise HTTPException(status_code=400, detail="no files submitted")
        root = Path(tempfile.mkdtemp(prefix="b2t_upload_"))
        _reconstruct(files, root)
        output_dir = root.parent / (root.name + "_out")
        job = jobs.create(input_dir=root, output_dir=output_dir)
        EXECUTOR.submit(
            run_job, jobs, job.id, root, output_dir, _make_converter(use_fake, model)
        )
        return JobCreated(job_id=job.id, status=job.status)

    @app.post("/api/jobs/sample", response_model=JobCreated)
    async def create_sample_job(use_fake: bool = Form(False), model: str = Form("")):
        output_dir = Path(tempfile.mkdtemp(prefix="b2t_sample_")) / "out"
        job = jobs.create(input_dir=SAMPLE_DECK, output_dir=output_dir)
        EXECUTOR.submit(
            run_job, jobs, job.id, SAMPLE_DECK, output_dir,
            _make_converter(use_fake, model),
        )
        return JobCreated(job_id=job.id, status=job.status)

    @app.get("/api/jobs/{job_id}", response_model=JobView)
    def get_job(job_id: str):
        job = jobs.get(job_id)
        if job is None:
            raise HTTPException(status_code=404, detail="unknown job")
        return to_view(job)

    @app.get("/api/jobs/{job_id}/typ")
    def get_typ(job_id: str):
        job = jobs.get(job_id)
        if job is None or job.typst_path is None:
            raise HTTPException(status_code=404, detail="no typst output")
        return PlainTextResponse(Path(job.typst_path).read_text(encoding="utf-8"))

    @app.get("/api/jobs/{job_id}/pdf")
    def get_pdf(job_id: str):
        job = jobs.get(job_id)
        if job is None or job.pdf_path is None or not Path(job.pdf_path).exists():
            raise HTTPException(status_code=404, detail="no pdf output")
        return FileResponse(Path(job.pdf_path), media_type="application/pdf")

    @app.post("/api/jobs/{job_id}/save", response_model=SaveResult)
    def save_job(job_id: str, req: SaveRequest):
        job = jobs.get(job_id)
        if job is None or job.typst_path is None:
            raise HTTPException(status_code=404, detail="no typst output to save")
        Path(job.typst_path).write_text(req.source, encoding="utf-8")
        result = compile_typst(Path(job.typst_path))
        if result.ok:
            jobs.update(
                job_id, status="succeeded", pdf_path=result.pdf_path, error=None
            )
        else:
            # Drop any stale PDF so a later download stays consistent with the
            # broken source (typst leaves the previous PDF in place on failure).
            Path(job.typst_path).with_suffix(".pdf").unlink(missing_ok=True)
            jobs.update(
                job_id, status="compile_failed", pdf_path=None, error=result.error
            )
        return SaveResult(ok=result.ok, error=result.error)

    @app.get("/api/jobs/{job_id}/download")
    def download_job(job_id: str):
        job = jobs.get(job_id)
        if job is None or job.output_dir is None or not Path(job.output_dir).exists():
            raise HTTPException(status_code=404, detail="no output to download")
        zip_path = _zip_dir(Path(job.output_dir))
        return FileResponse(
            zip_path, media_type="application/zip", filename="deck.zip"
        )

    @app.get("/api/models", response_model=ModelsView)
    def get_models():
        return ModelsView(
            models=[ModelOption(id=m.id, label=m.label) for m in OPEN_MODELS],
            default=DEFAULT_MODEL,
        )

    @app.get("/api/graph", response_model=GraphView)
    def get_graph():
        mermaid = build_graph(FakeConverter()).get_graph().draw_mermaid()
        return GraphView(mermaid=mermaid)

    app.mount("/", StaticFiles(directory=STATIC_DIR, html=True), name="static")
    return app


app = create_app()
