import json
import tempfile
import zipfile
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse, PlainTextResponse
from fastapi.staticfiles import StaticFiles
from loguru import logger

from b2t.api.jobs import EXECUTOR, JobStore, resume_job, run_job
from b2t.api.schemas import (
    GraphEdge,
    GraphNode,
    GraphView,
    JobCreated,
    JobView,
    LLMNodeView,
    LLMNodesView,
    ModelOption,
    ModelsView,
    NodeStateView,
    PromptContentView,
    RenderedPromptView,
    ReviewDecision,
    ReviewView,
    SampleDecksView,
    SaveRequest,
    SaveResult,
    VersionOption,
    to_view,
)
from b2t.api.state_view import fold_snapshot
from b2t import prompts
from b2t.graph import build_graph
from b2t.config import DEFAULT_MODEL, OPEN_MODELS, REPO_ROOT
from b2t.log import setup_logging
from b2t.typst_runner import compile_typst
from b2t.llm import FakeClient, LLMClient, OpenRouterClient

SAMPLE_DECKS_DIR = REPO_ROOT / "tests" / "fixtures" / "sample_decks"
STATIC_DIR = Path(__file__).parent / "static"
FAKE_TYPST = "== Sample\n\nGenerated by the fake converter.\n"


def _sample_deck_names() -> list[str]:
    """Return the bundled sample deck names (subdirectories), sorted."""
    return sorted(p.name for p in SAMPLE_DECKS_DIR.iterdir() if p.is_dir())


def _make_client(use_fake: bool) -> LLMClient:
    """Pick the client for a job.

    Args:
        use_fake: True for the offline FakeClient (no network).

    Returns:
        An LLMClient ready for the pipeline.
    """
    if use_fake:
        return FakeClient(FAKE_TYPST)
    return OpenRouterClient()


def _parse_choices(raw: str) -> dict:
    """Parse and validate the per-node choices JSON from a form field.

    Args:
        raw: JSON like {"convert": {"model": "...", "prompt_version": "v1"}};
            empty string means no overrides.

    Returns:
        The validated choices dict (empty if raw is empty).

    Raises:
        HTTPException: 400 if the JSON is invalid, names an unknown node, or
            names an unknown prompt version. Unknown models are allowed through.
    """
    if not raw:
        return {}
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        raise HTTPException(status_code=400, detail="choices is not valid JSON")
    valid_nodes = set(prompts.list_nodes())
    for node, sel in data.items():
        if node not in valid_nodes:
            raise HTTPException(status_code=400, detail=f"unknown LLM node: {node}")
        version = sel.get("prompt_version")
        if version and version not in prompts.list_versions(node):
            raise HTTPException(
                status_code=400, detail=f"unknown version {version} for node {node}"
            )
    return data


def _safe_target(root: Path, rel: str) -> Path:
    """Resolve rel under root, rejecting any path that escapes root.

    Args:
        root: Directory uploads must stay inside.
        rel: Relative path supplied by the client.

    Returns:
        The resolved absolute path under root.

    Raises:
        HTTPException: 400 if the path escapes root (e.g. via "..").
    """
    target = (root / rel).resolve()
    if not target.is_relative_to(root):
        raise HTTPException(status_code=400, detail="invalid path in upload")
    return target


def _reconstruct(files: list[UploadFile], root: Path) -> None:
    """Write each uploaded file under root at its relative path.

    Args:
        files: Multipart uploads whose filenames carry deck-relative paths.
        root: Destination directory for the reconstructed deck.
    """
    root = root.resolve()
    for upload in files:
        target = _safe_target(root, upload.filename or "")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(upload.file.read())


def _zip_dir(directory: Path) -> Path:
    """Zip every file under directory into a fresh temp zip.

    Args:
        directory: Directory whose files are archived (paths kept relative).

    Returns:
        Path to the created zip file in a new temporary directory.
    """
    zip_path = Path(tempfile.mkdtemp(prefix="b2t_download_")) / "deck.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(directory.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(directory))
    return zip_path


def create_app(store: JobStore | None = None) -> FastAPI:
    """Build the testing-UI FastAPI app.

    Args:
        store: Job registry to use; a fresh in-memory JobStore by default.

    Returns:
        The configured FastAPI application serving the API and static UI.
    """
    load_dotenv()
    setup_logging()
    app = FastAPI(title="b2t testing UI")
    jobs = store or JobStore()

    @app.post("/api/jobs", response_model=JobCreated)
    async def create_job(
        files: list[UploadFile] = File([]),
        use_fake: bool = Form(False),
        choices: str = Form(""),
        hitl: bool = Form(False),
    ):
        """Reconstruct an uploaded deck folder and start a conversion job."""
        if not files:
            raise HTTPException(status_code=400, detail="no files submitted")
        parsed = _parse_choices(choices)
        root = Path(tempfile.mkdtemp(prefix="b2t_upload_"))
        _reconstruct(files, root)
        output_dir = root.parent / (root.name + "_out")
        job = jobs.create(
            input_dir=root, output_dir=output_dir,
            hitl=hitl, use_fake=use_fake, choices=parsed,
        )
        logger.info("job {} created for upload ({} files)", job.id, len(files))
        EXECUTOR.submit(
            run_job, jobs, job.id, root, output_dir,
            lambda: _make_client(use_fake),
            parsed, hitl,
        )
        return JobCreated(job_id=job.id, status=job.status)

    @app.get("/api/sample-decks", response_model=SampleDecksView)
    def get_sample_decks():
        """Return the names of the bundled sample decks for the picker."""
        return SampleDecksView(decks=_sample_deck_names())

    @app.post("/api/jobs/sample", response_model=JobCreated)
    async def create_sample_job(
        use_fake: bool = Form(False),
        choices: str = Form(""),
        deck: str = Form(""),
        hitl: bool = Form(False),
    ):
        """Start a conversion job on a chosen bundled sample deck.

        `deck` names a subdirectory of the sample-decks folder; empty selects
        the first. An unknown name is rejected (this also guards traversal).
        """
        parsed = _parse_choices(choices)
        names = _sample_deck_names()
        name = deck or (names[0] if names else "")
        if name not in names:
            raise HTTPException(status_code=400, detail=f"unknown sample deck: {deck}")
        input_dir = SAMPLE_DECKS_DIR / name
        output_dir = Path(tempfile.mkdtemp(prefix="b2t_sample_")) / "out"
        job = jobs.create(
            input_dir=input_dir, output_dir=output_dir,
            hitl=hitl, use_fake=use_fake, choices=parsed,
        )
        logger.info("job {} created for sample deck {}", job.id, name)
        EXECUTOR.submit(
            run_job, jobs, job.id, input_dir, output_dir,
            lambda: _make_client(use_fake),
            parsed, hitl,
        )
        return JobCreated(job_id=job.id, status=job.status)

    @app.get("/api/jobs/{job_id}", response_model=JobView)
    def get_job(job_id: str):
        """Return the job's status, progress, and discovered files. 404 if unknown."""
        job = jobs.get(job_id)
        if job is None:
            raise HTTPException(status_code=404, detail="unknown job")
        return to_view(job)

    @app.get("/api/jobs/{job_id}/typ")
    def get_typ(job_id: str):
        """Return the generated main.typ as plain text. 404 if not produced yet."""
        job = jobs.get(job_id)
        if job is None or job.typst_path is None:
            raise HTTPException(status_code=404, detail="no typst output")
        return PlainTextResponse(Path(job.typst_path).read_text(encoding="utf-8"))

    @app.get("/api/jobs/{job_id}/pdf")
    def get_pdf(job_id: str):
        """Return the compiled PDF. 404 if compilation has not succeeded."""
        job = jobs.get(job_id)
        if job is None or job.pdf_path is None or not Path(job.pdf_path).exists():
            raise HTTPException(status_code=404, detail="no pdf output")
        return FileResponse(Path(job.pdf_path), media_type="application/pdf")

    @app.get("/api/jobs/{job_id}/prompt/{node}", response_model=RenderedPromptView)
    def get_rendered_prompt(job_id: str, node: str):
        """Return the exact prompt a node sent on this job's run. 404 if absent."""
        job = jobs.get(job_id)
        if job is None or node not in job.llm_rendered:
            raise HTTPException(status_code=404, detail="no rendered prompt")
        rendered = job.llm_rendered[node]
        run = job.llm_runs[node]
        return RenderedPromptView(
            node=node,
            model=run["model"],
            prompt_version=run["prompt_version"],
            system=rendered["system"],
            user=rendered["user"],
        )

    @app.get("/api/jobs/{job_id}/state/{node}", response_model=NodeStateView)
    def get_node_state(job_id: str, node: str):
        """Return the accumulated pipeline state after `node` ran. 404 if absent."""
        job = jobs.get(job_id)
        if job is None:
            raise HTTPException(status_code=404, detail="unknown job")
        try:
            changed, snapshot = fold_snapshot(job.seed_state, job.node_deltas, node)
        except KeyError:
            raise HTTPException(status_code=404, detail="node has not run")
        return NodeStateView(node=node, changed=changed, state=snapshot)

    @app.get("/api/jobs/{job_id}/review", response_model=ReviewView)
    def get_review(job_id: str):
        """Return the frame currently awaiting review. 404 if none."""
        job = jobs.get(job_id)
        if job is None or job.status != "awaiting_review" or job.review is None:
            raise HTTPException(status_code=404, detail="no frame awaiting review")
        return ReviewView(**job.review)

    @app.get("/api/jobs/{job_id}/preview.pdf")
    def get_preview(job_id: str):
        """Return the deck-so-far preview PDF. 404 if not produced."""
        job = jobs.get(job_id)
        if job is None or job.output_dir is None:
            raise HTTPException(status_code=404, detail="no preview")
        pdf = Path(job.output_dir) / "preview.pdf"
        if not pdf.exists():
            raise HTTPException(status_code=404, detail="no preview")
        return FileResponse(pdf, media_type="application/pdf")

    @app.post("/api/jobs/{job_id}/review", response_model=JobCreated)
    def submit_review(job_id: str, decision: ReviewDecision):
        """Resume a paused review with the reviewer's decision."""
        job = jobs.get(job_id)
        if job is None:
            raise HTTPException(status_code=404, detail="unknown job")
        if job.status != "awaiting_review":
            raise HTTPException(status_code=400, detail="job is not awaiting review")
        if decision.action not in {"approve", "regenerate"}:
            raise HTTPException(status_code=400, detail="invalid action")
        jobs.update(job_id, status="running")
        EXECUTOR.submit(
            resume_job, jobs, job_id, decision.action, decision.feedback,
            lambda: _make_client(job.use_fake),
        )
        return JobCreated(job_id=job_id, status="running")

    @app.post("/api/jobs/{job_id}/save", response_model=SaveResult)
    def save_job(job_id: str, req: SaveRequest):
        """Overwrite the job's main.typ with edited source and recompile it.

        Returns the compile outcome; on failure the stale PDF is removed so a
        later download stays consistent with the broken source.
        """
        job = jobs.get(job_id)
        if job is None or job.typst_path is None:
            raise HTTPException(status_code=404, detail="no typst output to save")
        Path(job.typst_path).write_text(req.source, encoding="utf-8")
        result = compile_typst(Path(job.typst_path))
        logger.info("job {} save-and-compile: ok={}", job_id, result.ok)
        if result.ok:
            jobs.update(
                job_id, status="succeeded", pdf_path=result.pdf_path, error=None
            )
        else:
            # Drop any stale PDF so a later download stays consistent with the
            # broken source (typst leaves the previous PDF in place on failure).
            Path(job.typst_path).with_suffix(".pdf").unlink(missing_ok=True)
            jobs.update(
                job_id, status="compile_failed", pdf_path=None, error=result.error
            )
        return SaveResult(ok=result.ok, error=result.error)

    @app.get("/api/jobs/{job_id}/download")
    def download_job(job_id: str):
        """Return the job's output directory as deck.zip. 404 if there is none."""
        job = jobs.get(job_id)
        if job is None or job.output_dir is None or not Path(job.output_dir).exists():
            raise HTTPException(status_code=404, detail="no output to download")
        zip_path = _zip_dir(Path(job.output_dir))
        return FileResponse(
            zip_path, media_type="application/zip", filename="deck.zip"
        )

    @app.get("/api/models", response_model=ModelsView)
    def get_models():
        """Return the model catalog as {id, label} options plus the default id."""
        return ModelsView(
            models=[ModelOption(id=m.id, label=m.label) for m in OPEN_MODELS],
            default=DEFAULT_MODEL,
        )

    @app.get("/api/llm-nodes", response_model=LLMNodesView)
    def get_llm_nodes():
        """Return each LLM node with its prompt versions and default version."""
        nodes = []
        for node in prompts.list_nodes():
            versions = [
                VersionOption(id=v, label=prompts.load(node, v).description or v)
                for v in prompts.list_versions(node)
            ]
            nodes.append(
                LLMNodeView(
                    node=node,
                    versions=versions,
                    default_version=prompts.default_version(node),
                )
            )
        return LLMNodesView(nodes=nodes)

    @app.get("/api/prompts/{node}/{version}", response_model=PromptContentView)
    def get_prompt_content(node: str, version: str):
        """Return a prompt version's system and user_template (read-only preview)."""
        if node not in prompts.list_nodes():
            raise HTTPException(status_code=404, detail="unknown LLM node")
        if version not in prompts.list_versions(node):
            raise HTTPException(status_code=404, detail="unknown prompt version")
        pv = prompts.load(node, version)
        return PromptContentView(
            node=node,
            version=version,
            description=pv.description,
            system=pv.system,
            user_template=pv.user_template,
        )

    @app.get("/api/graph", response_model=GraphView)
    def get_graph():
        """Return the pipeline topology (nodes with is_llm, plus edges).

        Derived from the real compiled graph, so it cannot drift from the
        pipeline; a node is an LLM node when its name is in the prompt registry.
        """
        graph = build_graph(FakeClient()).get_graph()
        llm = set(prompts.list_nodes())
        skip = {"__start__", "__end__"}
        nodes = [
            GraphNode(name=name, is_llm=name in llm)
            for name in graph.nodes
            if name not in skip
        ]
        edges = [
            GraphEdge(source=e.source, target=e.target)
            for e in graph.edges
            if e.source not in skip and e.target not in skip
        ]
        return GraphView(nodes=nodes, edges=edges)

    app.mount("/", StaticFiles(directory=STATIC_DIR, html=True), name="static")
    return app


app = create_app()
