import tempfile
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse, PlainTextResponse
from fastapi.staticfiles import StaticFiles

from b2t.api.jobs import EXECUTOR, JobStore, run_job
from b2t.api.schemas import (
    JobCreated,
    JobView,
    SaveRequest,
    SaveResult,
    to_view,
)
from b2t.config import REPO_ROOT
from b2t.typst_runner import compile_typst
from b2t.llm import ConverterLLM, FakeConverter, OpenAIConverter

SAMPLE_DECK = REPO_ROOT / "tests" / "fixtures" / "sample_deck"
STATIC_DIR = Path(__file__).parent / "static"
FAKE_TYPST = (
    "#set page(width: 16cm, height: 9cm)\n"
    "= Sample\n\nGenerated by the fake converter.\n"
)


def _make_converter(use_fake: bool, model: str) -> ConverterLLM:
    if use_fake:
        return FakeConverter(FAKE_TYPST)
    return OpenAIConverter(model=model or None)


def _safe_target(root: Path, rel: str) -> Path:
    """Resolve rel under root, rejecting any path that escapes root."""
    target = (root / rel).resolve()
    if not target.is_relative_to(root):
        raise HTTPException(status_code=400, detail="invalid path in upload")
    return target


def _reconstruct(files: list[UploadFile], root: Path) -> None:
    """Write each uploaded file under root at its relative path. Reject escapes."""
    root = root.resolve()
    for upload in files:
        target = _safe_target(root, upload.filename or "")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(upload.file.read())


def create_app(store: JobStore | None = None) -> FastAPI:
    load_dotenv()
    app = FastAPI(title="b2t testing UI")
    jobs = store or JobStore()

    @app.post("/api/jobs", response_model=JobCreated)
    async def create_job(
        files: list[UploadFile] = File([]),
        use_fake: bool = Form(False),
        model: str = Form(""),
    ):
        if not files:
            raise HTTPException(status_code=400, detail="no files submitted")
        root = Path(tempfile.mkdtemp(prefix="b2t_upload_"))
        _reconstruct(files, root)
        output_dir = root.parent / (root.name + "_out")
        job = jobs.create(input_dir=root, output_dir=output_dir)
        EXECUTOR.submit(
            run_job, jobs, job.id, root, output_dir, _make_converter(use_fake, model)
        )
        return JobCreated(job_id=job.id, status=job.status)

    @app.post("/api/jobs/sample", response_model=JobCreated)
    async def create_sample_job(use_fake: bool = Form(False), model: str = Form("")):
        output_dir = Path(tempfile.mkdtemp(prefix="b2t_sample_")) / "out"
        job = jobs.create(input_dir=SAMPLE_DECK, output_dir=output_dir)
        EXECUTOR.submit(
            run_job, jobs, job.id, SAMPLE_DECK, output_dir,
            _make_converter(use_fake, model),
        )
        return JobCreated(job_id=job.id, status=job.status)

    @app.get("/api/jobs/{job_id}", response_model=JobView)
    def get_job(job_id: str):
        job = jobs.get(job_id)
        if job is None:
            raise HTTPException(status_code=404, detail="unknown job")
        return to_view(job)

    @app.get("/api/jobs/{job_id}/typ")
    def get_typ(job_id: str):
        job = jobs.get(job_id)
        if job is None or job.typst_path is None:
            raise HTTPException(status_code=404, detail="no typst output")
        return PlainTextResponse(Path(job.typst_path).read_text(encoding="utf-8"))

    @app.get("/api/jobs/{job_id}/pdf")
    def get_pdf(job_id: str):
        job = jobs.get(job_id)
        if job is None or job.pdf_path is None or not Path(job.pdf_path).exists():
            raise HTTPException(status_code=404, detail="no pdf output")
        return FileResponse(Path(job.pdf_path), media_type="application/pdf")

    @app.post("/api/jobs/{job_id}/save", response_model=SaveResult)
    def save_job(job_id: str, req: SaveRequest):
        job = jobs.get(job_id)
        if job is None or job.typst_path is None:
            raise HTTPException(status_code=404, detail="no typst output to save")
        Path(job.typst_path).write_text(req.source, encoding="utf-8")
        result = compile_typst(Path(job.typst_path))
        if result.ok:
            jobs.update(
                job_id, status="succeeded", pdf_path=result.pdf_path, error=None
            )
        else:
            jobs.update(
                job_id, status="compile_failed", pdf_path=None, error=result.error
            )
        return SaveResult(ok=result.ok, error=result.error)

    app.mount("/", StaticFiles(directory=STATIC_DIR, html=True), name="static")
    return app


app = create_app()
